In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [62]:
data = pd.read_csv("/content/drive/My Drive/Colab/creditcard/UCI_Credit_Card.csv")

In [30]:
data.head()

ID  LIMIT_BAL  SEX  ...  PAY_AMT5  PAY_AMT6  default.payment.next.month
0   1    20000.0    2  ...       0.0       0.0                           1
1   2   120000.0    2  ...       0.0    2000.0                           1
2   3    90000.0    2  ...    1000.0    5000.0                           0
3   4    50000.0    2  ...    1069.0    1000.0                           0
4   5    50000.0    1  ...     689.0     679.0                           0

[5 rows x 25 columns]

In [31]:
x = data.iloc[:,1:-1].values
y = data.iloc[:,-1].values
y=y.ravel()

In [32]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 10)

In [33]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [34]:
from sklearn.decomposition import PCA
pca = PCA()
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)


In [35]:
from sklearn.linear_model import LogisticRegression
lr  = LogisticRegression()
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)   

In [36]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[4566  117]
 [1006  311]]
              precision    recall  f1-score   support

           0       0.82      0.98      0.89      4683
           1       0.73      0.24      0.36      1317

    accuracy                           0.81      6000
   macro avg       0.77      0.61      0.62      6000
weighted avg       0.80      0.81      0.77      6000



In [37]:
from sklearn.naive_bayes import GaussianNB
nb  = GaussianNB()
nb.fit(x_train,y_train)
y_pred_nb = nb.predict(x_test)

In [38]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred_nb))
print(classification_report(y_test,y_pred_nb))

[[3443 1240]
 [ 478  839]]
              precision    recall  f1-score   support

           0       0.88      0.74      0.80      4683
           1       0.40      0.64      0.49      1317

    accuracy                           0.71      6000
   macro avg       0.64      0.69      0.65      6000
weighted avg       0.77      0.71      0.73      6000



In [39]:
from sklearn.ensemble import RandomForestClassifier
rf  = RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred_rf = rf.predict(x_test)

In [40]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred_rf))
print(classification_report(y_test,y_pred_rf))

[[4432  251]
 [ 849  468]]
              precision    recall  f1-score   support

           0       0.84      0.95      0.89      4683
           1       0.65      0.36      0.46      1317

    accuracy                           0.82      6000
   macro avg       0.75      0.65      0.67      6000
weighted avg       0.80      0.82      0.80      6000



In [97]:
import keras
from keras.models import Sequential
from keras.layers import Dense


In [98]:
classifier = Sequential()
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 23))
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [99]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


In [100]:
classifier.fit(x_train, y_train, batch_size = 10, epochs = 200)


Epoch 1/200
24000/24000 [==============================] - 3s 110us/step - loss: 0.4892 - accuracy: 0.7785
Epoch 2/200
24000/24000 [==============================] - 3s 105us/step - loss: 0.4693 - accuracy: 0.8050
Epoch 3/200
24000/24000 [==============================] - 3s 105us/step - loss: 0.4677 - accuracy: 0.8079
Epoch 4/200
24000/24000 [==============================] - 3s 104us/step - loss: 0.4670 - accuracy: 0.8075
Epoch 5/200
24000/24000 [==============================] - 3s 106us/step - loss: 0.4667 - accuracy: 0.8085
Epoch 6/200
24000/24000 [==============================] - 3s 104us/step - loss: 0.4662 - accuracy: 0.8092
Epoch 7/200
24000/24000 [==============================] - 3s 106us/step - loss: 0.4662 - accuracy: 0.8100
Epoch 8/200
24000/24000 [==============================] - 3s 105us/step - loss: 0.4661 - accuracy: 0.8109
Epoch 9/200
24000/24000 [==============================] - 3s 106us/step - loss: 0.4658 - accuracy: 0.8104
Epoch 10/200
24000/24000 [===========

In [101]:
y_pred = classifier.predict(x_test)
y_pred = (y_pred > 0.5)

In [102]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[4478  205]
 [ 862  455]]
              precision    recall  f1-score   support

           0       0.84      0.96      0.89      4683
           1       0.69      0.35      0.46      1317

    accuracy                           0.82      6000
   macro avg       0.76      0.65      0.68      6000
weighted avg       0.81      0.82      0.80      6000



EXTRA -- FEATURE IMPORTANCE 

In [65]:
x = data.iloc[:,1:-1]

In [66]:
from sklearn.ensemble import ExtraTreesClassifier
model = ExtraTreesClassifier(n_estimators=10)
model.fit(x, y)
print(model.feature_importances_)

[0.06533314 0.00819044 0.03308401 0.02334473 0.06573587 0.10265562
 0.05238909 0.02578031 0.03172577 0.0305346  0.02582029 0.05043349
 0.04675587 0.04510776 0.04469544 0.04282461 0.04465056 0.04352857
 0.04452716 0.04120177 0.04144608 0.04386712 0.04636769]


In [76]:
d = pd.DataFrame(data = model.feature_importances_, index = x.columns,columns =[ "Feature_importance"] )
d

Feature_importance
LIMIT_BAL            0.065333
SEX                  0.008190
EDUCATION            0.033084
MARRIAGE             0.023345
AGE                  0.065736
PAY_0                0.102656
PAY_2                0.052389
PAY_3                0.025780
PAY_4                0.031726
PAY_5                0.030535
PAY_6                0.025820
BILL_AMT1            0.050433
BILL_AMT2            0.046756
BILL_AMT3            0.045108
BILL_AMT4            0.044695
BILL_AMT5            0.042825
BILL_AMT6            0.044651
PAY_AMT1             0.043529
PAY_AMT2             0.044527
PAY_AMT3             0.041202
PAY_AMT4             0.041446
PAY_AMT5             0.043867
PAY_AMT6             0.046368